name: Dev deployment

on:
  pull_request:
    types: [labeled]

env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_DEPLOYMENT: "dev"
  PARAMS: "templates/dev.parameters.json"
  TEMPLATE: "templates/spa.json"

jobs:
  deploy-dev-app:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'deploy dev app')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure deployment
        if: success()
        run: |
          az deployment group create --name ${{env.AZURE_DEPLOYMENT}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --template-file ${{env.TEMPLATE}} --parameters ${{ env.PARAMS }} --parameters repositoryToken=${{ secrets.GH_PAT_AZURE }}
